// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHaMTlNqdec4cB2DdDI4Xal0wqH7NpcaA',
    appId: '1:171688641064:web:2597a114ef1749228feb1d',
    messagingSenderId: '171688641064',
    projectId: 'fruit-hup-2ec9c',
    authDomain: 'fruit-hup-2ec9c.firebaseapp.com',
    storageBucket: 'fruit-hup-2ec9c.firebasestorage.app',
    measurementId: 'G-9KXMPCERP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJ3f2jo-vcngfsFqoD8wEO8AkTk20gmk',
    appId: '1:171688641064:android:c22423edf086afca8feb1d',
    messagingSenderId: '171688641064',
    projectId: 'fruit-hup-2ec9c',
    storageBucket: 'fruit-hup-2ec9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQO1yHpkrqhvAVDrangs8pMpp-FUqt_tA',
    appId: '1:171688641064:ios:206ae2d9efa345038feb1d',
    messagingSenderId: '171688641064',
    projectId: 'fruit-hup-2ec9c',
    storageBucket: 'fruit-hup-2ec9c.firebasestorage.app',
    iosBundleId: 'com.example.frutesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQO1yHpkrqhvAVDrangs8pMpp-FUqt_tA',
    appId: '1:171688641064:ios:206ae2d9efa345038feb1d',
    messagingSenderId: '171688641064',
    projectId: 'fruit-hup-2ec9c',
    storageBucket: 'fruit-hup-2ec9c.firebasestorage.app',
    iosBundleId: 'com.example.frutesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHaMTlNqdec4cB2DdDI4Xal0wqH7NpcaA',
    appId: '1:171688641064:web:5c4fcf077ef7cf9c8feb1d',
    messagingSenderId: '171688641064',
    projectId: 'fruit-hup-2ec9c',
    authDomain: 'fruit-hup-2ec9c.firebaseapp.com',
    storageBucket: 'fruit-hup-2ec9c.firebasestorage.app',
    measurementId: 'G-VTHK79BRBM',
  );
}
